#target: prerrequisites
#	command to build target

# Variables de entorno



# crear el comando de compilación para modulos con archivo de salida
# iverilog -g2012 -Wall -o bin/nombre_ejeucutable nombre_archivo.v

# crear el comando de compilación para modulos sin archivo de salida
# iverilog -g2012 -Wall nombre_archivo.v

# crear el comando de compilación para testbenches
# iverilog -g2012 -Wall -s testbench_ejemplo -o archivo_simulación ejemplo.v testbench_ejemplo.v

# crear comando de ejecución
# vvp bin/nombre_ejecutable


help:
	@echo Ayuda